name: First Workflow
on: workflow_dispatch #Events to manually start workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Done - bye!"
